version: '3.8'

services:
  redis:
    image: redis
    container_name: redis

  frontend:
    build: ./example-frontend
    ports:
      - 3000:3000
    container_name: frontend
    depends_on:
      - backend

  backend:
    build: ./example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgres
      - REQUEST_ORIGIN=http://localhost
    container_name: backend
    depends_on:
      - redis
      - db

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: db
    volumes:
      - database:/var/lib/postgresql/data

  nginx:
    image: nginx:1.19.10-alpine
    restart: unless-stopped
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  database:
