version: '3.8'

services:
  redis:
    image: redis
    container_name: redis

  frontend:
    build: ./example-frontend
    ports:
      - 3000:3000
    container_name: front

  backend:
    build: ./example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
    container_name: back
